
spring:
  profiles:
    active: prod
---
server:
  port: 8201
spring:
  profiles: dev  #开发环境
  application:
    name: springcloud-study-config-client

---
server:
  port: 8202
spring:
  profiles: prod #开发环境
  application:
    name: springcloud-study-config-client


#请保存为UTF-8格式
